version: "3.9"

services:
  api:
    image: backend
    container_name: antimal-rescue-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5113:5113"
    env_file:
      - backend/.env.local
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
