version: "3.4"

services:
  api:
    image: backend
    container_name: animal-rescue-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5113:5113"
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AnimalRescueDbContext=Server=db;Database=arserbia;user id=sa;password=MySecret123!hahaha;
      - JwtAuthentication__Key="[DONOTCOMMITDONOTCOMMITDONOTCOMMITDONOTCOMMIT]"
      - JwtAuthentication__Salt="[DONOTCOMMITDONOTCOMMITDONOTCOMMITDONOTCOMMIT]"
    volumes:
      - "./uploads:/app/uploads"
  web:
    image: web
    container_name: animal-rescue-web
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
      - API_URL=http://localhost:5113 
    ports:
      - "3000:3000"

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: animal-rescue-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MySecret123!hahaha
    volumes:
      - ".:/app:rw"
