version: "3.4"

services:
  api:
    image: codeforacause/animal-rescue-serbia-app:backend-#{TAG_NUMBER}#
    container_name: animal-rescue-api
    ports:
      - "22001:5113"
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__AnimalRescueDbContext=Server=db;Database=arserbia;user id=sa;password=#{DB_PASSWORD}#;
      - Cors__Origins__0=https://ars.codeforacause.rs
      - JwtAuthentication__Key="#{JWT_KEY}#"
      - JwtAuthentication__Salt="#{JWT_SALT}#"
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/wwwroot/uploads:/app/wwwroot/uploads
    restart: always
  web:
    image: codeforacause/animal-rescue-serbia-app:web-#{TAG_NUMBER}#
    container_name: animal-rescue-web
    ports:
      - "22000:3000"
    restart: always
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: animal-rescue-db
    user: root
    ports:
      - 1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=#{DB_PASSWORD}#
    volumes:
      - ars_db:/var/opt/mssql/data
    restart: always
volumes:
  ars_db:
