name: CI
on:
  push:
    branches:
      - main
jobs:
  Main_branch:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main
      - name: Building docker image backend
        run: docker build ./backend/ -t codeforacause/animal-rescue-serbia-app:backend-${{ github.run_number }}
      - name: Building docker image web
        run: docker build ./web/ -t codeforacause/animal-rescue-serbia-app:web-${{ github.run_number }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pushing docker image to CR backend
        run: docker push codeforacause/animal-rescue-serbia-app:backend-${{ github.run_number }}
      - name: Pushing docker image to CR web
        run: docker push codeforacause/animal-rescue-serbia-app:web-${{ github.run_number }}
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["**docker-compose.animal-rescue-serbia.yaml"]'
        env:
          TAG_NUMBER: "${{ github.run_number }}"
          DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
          JWT_KEY: "${{ secrets.JWT_KEY }}"
          JWT_SALT: "${{ secrets.JWT_SALT }}"
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "docker-compose.animal-rescue-serbia.yaml"
          target: "./Projects/animal-rescue-serbia-app/"
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: docker-compose -f ./Projects/animal-rescue-serbia-app/docker-compose.animal-rescue-serbia.yaml up -d
          
